# Generated by Django 5.2 on 2025-05-11 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cards")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
