# Generated by Django 5.2 on 2025-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allcards",
            name="type",
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="allcards",
            name="urls",
            field=models.URLField(blank=True, null=True, verbose_name="Website URL"),
        ),
        migrations.AlterField(
            model_name="allcards",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cards"),
        ),
    ]
