# Generated by Django 5.2 on 2025-06-03 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0002_allcards_type_allcards_urls_alter_allcards_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="cards")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("position", models.CharField(max_length=100)),
            ],
        ),
    ]
