# Generated by Django 5.2 on 2025-06-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("component", "0003_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allcards",
            old_name="title",
            new_name="name",
        ),
    ]
