# Generated by Django 5.2 on 2025-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_rename_title_allcards_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcards',
            name='urls',
        ),
        migrations.AddField(
            model_name='allcards',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
