# Generated by Django 5.2 on 2025-06-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_remove_allcards_urls_allcards_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcards',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='allcards',
            name='urls',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
