# Generated by Django 5.2 on 2025-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0006_remove_allcards_pdf_file_allcards_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
