# Generated by Django 5.2 on 2025-06-25 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0007_members_email_members_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('urls', models.URLField(blank=True, max_length=300, null=True)),
                ('type', models.TextField(max_length=100)),
            ],
        ),
    ]
